// alert("olá seja bem vindo")
console.log("posso escrever aqui também")
console.log(10+2)
console.log(10-2)
console.log(10*2)
console.log(10/5)
console.log(parseFloat("10") + 2)
console.log("João" + " " + "Paulo")